### ISSUE TITLE
Let users nominate seasonals

### ISSUE THREAD

**Issue by Robin-M** [janvernieuwe/sotw-bot#5]
In #seasonal-anime worden nu een stel series uitgekozen door de admins. De praktijk wijst uit dat voor sommige series amper interesse is, terwijl andere nieuwe series die niet in de lijst staan mogelijk wel genoeg kijkers hebben.

Idee: maak #seasonal-anime een nominatie channel voor iedereen.
Stap 1: validatie. Een nominatie moet een correcte url zijn, type = TV en startdatum in huidige of vorige maand.
Stap 2: indien een correcte nominatie dan blijft deze staan en mogen anderen erop stemmen.
Stap 3: indien een stem ervoor zorgt dat de kijkdrempel (bijv. 10) wordt gehaald, dan wordt een nieuwe channel aangemaakt. De name is de title toLowerCase(), replaceAll(" ", "-"), substring voor afkapping lange titels (evt. kan die later manueel worden aangepast). Iedereen met een stem krijgt toegang. 
Stap 4: De nominatie wordt verwijderd en vervangen door de JoinableChannelMessage.

**Comment by janvernieuwe** [comment]
Als er interesse is, kunnen ze gewoon aangevraagd worden.
Tenminste zo lang we niet aan de channel limit zitten, anders wisselen we wel wat
